/**
 * Assembles the full meeting markdown body returned by `get_meeting` and by
 * the `meeting://<run_id>` resource. Order privileges raw user-authored and
 * raw transcript content over auto-generated summary content — small models
 * lose threads when summarizing, so the auto-summary is demoted and labeled.
 */
import type Database from "better-sqlite3";
import fs from "node:fs";
import path from "node:path";

export type MeetingSection = "notes" | "transcript" | "prep" | "summary";

export const DEFAULT_SECTION_ORDER: MeetingSection[] = [
  "notes",
  "transcript",
  "prep",
  "summary",
];

const SECTION_FILES: Record<MeetingSection, string> = {
  notes: "notes.md",
  transcript: "transcript.md",
  prep: "prep.md",
  summary: "summary.md",
};

const SECTION_HEADERS: Record<MeetingSection, string> = {
  notes: "## Notes (user-authored)",
  transcript: "## Transcript (raw)",
  prep: "## Prep (pre-meeting context)",
  summary:
    "## Auto-generated summary\n_Generated by the local summarization model; may miss threads. Prefer the transcript above for nuanced questions._",
};

export interface MeetingBodyMeta {
  run_id: string;
  title: string;
  date: string;
  participants: string[];
  duration_minutes: number | null;
}

export interface MeetingBody extends MeetingBodyMeta {
  body_md: string;
  sections_included: MeetingSection[];
}

export interface MeetingRow {
  run_id: string;
  title: string;
  date: string;
  duration_minutes: number | null;
  folder_path: string;
  participants: string[];
}

export function loadMeetingRow(
  db: Database.Database,
  runId: string
): MeetingRow | null {
  const row = db
    .prepare(
      `SELECT run_id, title, date, duration_minutes, folder_path
       FROM runs WHERE run_id = ?`
    )
    .get(runId) as
    | {
        run_id: string;
        title: string;
        date: string;
        duration_minutes: number | null;
        folder_path: string;
      }
    | undefined;
  if (!row) return null;

  let participants: string[] = [];
  try {
    const rows = db
      .prepare(
        `SELECT COALESCE(p.first_name || ' ' || p.last_name, p.first_name, p.email, '') AS label
         FROM run_participants rp
         INNER JOIN participants p ON p.participant_id = rp.participant_id
         WHERE rp.run_id = ?`
      )
      .all(runId) as Array<{ label: string }>;
    participants = rows.map((r) => r.label.trim()).filter(Boolean);
  } catch {
    // best-effort
  }

  return {
    run_id: row.run_id,
    title: row.title,
    date: row.date,
    duration_minutes: row.duration_minutes,
    folder_path: row.folder_path,
    participants,
  };
}

export interface AssembleOptions {
  /** Validate that the folder lives under this root before reading any file. */
  runsRoot: string;
  /** Subset of sections to include; defaults to all in DEFAULT_SECTION_ORDER. */
  sections?: MeetingSection[];
}

export function assembleMeetingBody(
  row: MeetingRow,
  opts: AssembleOptions
): MeetingBody {
  if (!isPathWithin(opts.runsRoot, row.folder_path)) {
    // Refuse to read content outside the configured runs root. The same
    // guardrail the app enforces (run-access.ts) — preserves the local
    // path-validation contract from the MCP layer.
    throw new Error(
      `Run folder ${row.folder_path} is outside the configured runs root ${opts.runsRoot}.`
    );
  }
  const sections = opts.sections ?? DEFAULT_SECTION_ORDER;
  const blocks: string[] = [];
  blocks.push(`# ${row.title} — ${row.date}`);
  if (row.participants.length > 0) {
    blocks.push(`_Participants: ${row.participants.join(", ")}_`);
  }
  if (row.duration_minutes != null) {
    blocks.push(`_Duration: ${formatDuration(row.duration_minutes)}_`);
  }
  blocks.push("");

  const included: MeetingSection[] = [];
  for (const section of sections) {
    const fname = SECTION_FILES[section];
    const fpath = path.join(row.folder_path, fname);
    let body: string | null = null;
    try {
      if (fs.existsSync(fpath)) body = fs.readFileSync(fpath, "utf-8").trim();
    } catch {
      // best-effort — a single section read failure shouldn't abort the
      // whole body assembly.
    }
    if (!body) continue;
    blocks.push(SECTION_HEADERS[section]);
    blocks.push("");
    blocks.push(body);
    blocks.push("");
    included.push(section);
  }

  return {
    run_id: row.run_id,
    title: row.title,
    date: row.date,
    participants: row.participants,
    duration_minutes: row.duration_minutes,
    body_md: blocks.join("\n").trim() + "\n",
    sections_included: included,
  };
}

function formatDuration(mins: number): string {
  if (mins < 60) return `${Math.round(mins)} min`;
  const hours = Math.floor(mins / 60);
  const rem = Math.round(mins - hours * 60);
  return rem === 0 ? `${hours}h` : `${hours}h ${rem}min`;
}

function isPathWithin(root: string, candidate: string): boolean {
  const normRoot = path.resolve(root);
  const normCandidate = path.resolve(candidate);
  if (normCandidate === normRoot) return true;
  const rel = path.relative(normRoot, normCandidate);
  return !rel.startsWith("..") && !path.isAbsolute(rel);
}
